spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/product-realm
          
          
keycloak:
  realm: product-realm
  auth-server-url: http://localhost:8080/auth
  resource: product-client
  credentials:
    secret: EkWtPOwamCt8LzCIJhNXkiiI7Hc7X9i0
    
logging:
  level:
    org.springframework.security: DEBUG